### ISSUE TITLE
Add ability to annotate the queries that are routed to ReadySet

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset-rails#14]
**Brief Description of Feature:**
Rails already logs to stdout any queries that are being executed in the `development` environment. To make it easy for people to see which queries are going to ReadySet, we should augment these log lines to include something like `(ReadySet)` at the end of the line to make it easy for users to verify that queries are being routed.

**Background:**
Currently, the only way to verify that a given query was routed to ReadySet is by invoking `Readyset::Query.all_seen_but_not_cached_queries`. I think we should prevent users from having to mess around with the `Readyset::Query` methods as much as possible. Including information in the query logs that Rails already emits will give users information for free without having to inspect state manually.

---
## Optional information to add

**Proposed Solution:**
We may be able to take advantage of `ActiveSupport::Notification`s for this purpose like this: https://github.com/aglover/locution/blob/a3974a2f4bc8c85639018c8883950b8a574fae0f/config/initializers/ready_set_listener.rb#L3-L15

That would let us log an _extra_ line to show that a query was routed to ReadySet, but it wouldn't let us make changes to the log line itself. There may well be a better way to do this, so more research is needed.

**Comment by helpotters** [comment]
Started work on this front. Trying to keep it flexible so it can tag queries from any source, and also include ReadySet-specific context tags. We shall see.

This could possibly hook up with another thing that appends uncached-but-rerouted queries to a file, including source comments, and maybe that could be used to generate a caching-migration file? Idk, lemme know what you think.

**Comment by ethan-readyset** [comment]
As discussed today, I intended this ticket to mean logging queries to the Rails logs (e.g. stdout) -- not tagging queries and storing them somewhere for the purposes of determining their origin. I know Rails supports logging _all_ queries to stdout as they are invoked, but I was thinking it might be useful for users to log only those queries that are routed to ReadySet. This could be used to help users understand what queries are being invoked in different code paths.

**Comment by ethan-readyset** [comment]
I updated the description above to reflect this -- apologies for the misunderstanding! I'm going to remove this ticket from milestone one for the time being. I'm not totally convinced this will be that useful, given that users would be seeing raw query strings in the logs anyway.

**Comment by helpotters** [comment]
Based off our conversation, I'll be opening separate "Logger" interface issue to investigate whether or not that's essential.
 
I'll relabel this issue in terms of "tagging" queries with annotations to indicate it has been routed to ReadySet.
