### ISSUE TITLE
Revamp README

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset-rails#16]
**Brief Description of Feature:**
We should rewrite our README from the ground up to reflect the current state of the gem.

**Background:**
Our README should briefly describe what ReadySet is, describe what the gem does, and document the gem's features in detail. The README will be our opportunity to make a great first impression, so it should make our gem's functionality crystal clear. Any caveats or potential pain points should be clearly called out to make sure users are not confused about behavior.

The README may also be the first time people hear of ReadySet, so we should be sure to include a concise and easy to understand description of ReadySet's value proposition right at the beginning. That said, we should rely on links to `docs.readyset.io` for more in-depth information so as not to overload our README with too much information that is not relevant to the gem.

**Detailed Explanation:**
The outline of the README should look something like this:

* Title + brief tagline like "A gem for caching with [ReadySet](https://readyset.io/) within Rails applications"
* What is ReadySet? (a brief description of ReadySet with links to more information)
* What does this gem do? (explain the motivation for the gem at a high level. explain that by caching within the context of your app, you are able to route only cached queries to ReadySet. the rest of your queries go straight to your database)
* Installing
* Quick Start: I think we should lead with the "named caches" feature and just list a few steps with code blocks as examples, something like:
    1. Add the gem to your `Gemfile` or run `bundle add readyset`
    2. Run `rails generate readyset:install` (I thought it would be nice to include a generator that generates a skeleton config file for users)
    3. Add a "readyset" section to your `config/databases.yml` with your connection info
    4. To route to ReadySet all of the queries in the `show` action for one of your controllers, add the following to the top of the controller:
    ```ruby
    class UserController < ActionController
      route_to_readyset only: :show

      ...
    end
    ```
    5. Start up your application and hit the endpoint that invokes that controller action
    6. Run `rails readyset:synchronize_caches` to create the cache on ReadySet
    7. Experience lightning fast queries!
* Features
    * Routing and caching queries in arbitrary blocks of code (`Readyset.route`)
        * Explain `Readyset.route`  -- it routes queries to ReadySet but does not automatically cache them
        * Explain that we don't know about the queries wrapped by ReadySet.route until the query is actually executed for the first time
        * Explain that you can dump all of the caches created via ReadySet.route to a "migration file" by running `rails readyset:create_migration_file`
    *. `route_to_readyset` controller annotation
    * `readyset_query` model annotation 
    * Creating and dropping caches via ActiveRecord's query interface
        * Talk about `YourModel.where(...).create_readyset_cache!` and `YourModel.where(...).drop_readyset_cache!`
* Using ReadySet as your primary database connection (explain how to configure the gem to allow for this)
* Configuration (detailed configuration options)
* License (brief section describing our MIT license a la [this example](https://github.com/heartcombo/devise#license))

**Comment by helpotters** [comment]
I'd like to tackle to this to write with a junior-dev onboarding/first-try strategy in mind. I may get started on this sooner rather than later so it can guide testing, especially regarding console commands.
