### ISSUE TITLE
Add query routing for models

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset-rails#3]
**Brief Description of Feature:**
We should add an `ActiveRecord::Base` extension that allows users to route queries in models similar to the controller extension we are adding in #28. 

**Background:**
Users may already know which queries they want to cache. If the same query is invoked in multiple places, they would need to manually wrap that query in `Readyset.route { ... }` in all of those places. Adding an easy way to DRY this up via an extension to `ActiveRecord::Base` reduces the chances that users will mistakenly send cached queries to their database.

---
## Optional information to add

**Proposed Solution:**
We should add a `Readyset::ModelExtension` module that defines a `readyset_query` class method. When invoked in the class body of a model, it would define a new class method that invokes the given query in the context of a `Readyset.route` block. The syntax should be similar to that of scopes:
```ruby
class Word < ApplicationRecord
  readyset_query :nouns, -> { where(part_of_speech: 'noun') }
end
```

**Comment by ethan-readyset** [comment]
Notably, we cannot support caching scopes because a scope represents a potentially unfinished query

**Comment by helpotters** [comment]
The connected_to interface is probably the best approach. We just added the controller around_action for it, so I could try adding a way to pass arbitrary blocks to be performed under the "ReadySet context".
