### ISSUE TITLE
Use connection pool instead of `establish_connection` [feature]

### ISSUE THREAD

**Issue by helpotters** [readysettech/readyset-rails#52]
**Brief Description of Feature:**
[Provide a concise description of the feature you want to add.]
- Improve performance and thread-safety by changing how we connect to the replica database to issue commands.
- Switch to using connection pool instead making a new connection per query to Readyset.

**Background:**
[Include any relevant background information or context that led to this feature request.]

- Currently, [`raw_query`](https://github.com/readysettech/readyset-rails/blob/df6b396395e44f2767734c29c147ebbc370faa84/lib/readyset.rb#L17C1-L17C96) uses `ActiveRecord::Base.establish_connection` to connect to Readyset.
- **How Connection Pool Works**: each thread checks out a connection and checks it back in when its done
- `#establish_connection` creates a new connection, which may include any new settings.
  - for connecting to a *new* database  
  - for changing the connection settings  
  - might not scale correctly
  - might affect thread-safety
- `#connection` will using an existing connection from the pool.

**Detailed Explanation:**
[Provide a detailed explanation of the feature, including how it should work and its expected behavior.]

- Establish a database connection pool 
  - Create a `ConnectionSpec` object based off of `Readyset.configuration.connection_url`
  - Create connection pool 

**From the user's perspective:**
[How will the user interact with this feature? Reference any current limitations that this feature will address, including any subjective opinions regarding the developer-experience.]

- This will [concurrency](https://devcenter.heroku.com/articles/concurrency-and-database-connections) to the gem, improving performance on multi-threaded or multi-processed servers. 
- Could lead to additional configuration options for users (`ConnectionSpec`). 
---
## Optional information to add

**Proposed Solution:**
[Describe your proposed solution, including technical details, if applicable. Multiple ideas are okay too. Or just roughly describe what a successful implementation would look like.]

```
  def self.replica_connection_pool
    @replica_connection_pool ||= create_replica_connection_pool
  end

  private

  def self.create_replica_connection_pool
    # Create a hash with the connection URL
    configurations = { 'replica' => configuration.connection_url }

    # Use the Resolver to parse the URL into a connection configuration hash
    resolver = ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver.new(configurations)
    resolved_config = resolver.resolve('replica')

    # Create and return a connection pool with the resolved configuration
    spec = ActiveRecord::ConnectionAdapters::ConnectionSpecification.new(resolved_config, 'replica_spec')
    ActiveRecord::ConnectionAdapters::ConnectionPool.new(spec)
  end
```
- Needs to be cleaned up and tested
- Uses URL and `ConnectionSpecficiation::Resolver` to make a new connection spec for the `ConnectionPool`. 

**Benefits / Pros:**
[List the benefits of implementing this feature. Explain how it will improve the user experience, performance, or functionality of the Ruby gem.]

- Improve performance, especially with multi-process applications
- Improve thread-safety, as each thread pulls a single connection from the pool.

**Potential Drawbacks / Cons:**
[Discuss any potential drawbacks or negative impacts of the proposed feature.]

-  Introduces additional complexity by having a connection pool
-  May require careful testing?

**Comment by ethan-readyset** [comment]
Closing this as we moved away from using `establish_connection` in https://github.com/readysettech/readyset-rails/commit/6e796494c751ce32f3555bff8ad6a4529b3a73b1
